# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2dec9df113b9486ff2998b727adb03897bf3aaf043c4115b13acf77470728e4110de6c63cfc438cdaf862382ec0687c218975947587ea908c43b2d794c72b364

test:
  secret_key_base: 0887c5be1c0c3d5808dd2d82a25caf1113b46a6b304bb428c776dace896e292368ce87ea70354aa670fb444895886ee6f1105d91ef3985ad146248f78c077993

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
